name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build build --config Debug
    - name: Test
      run: |
        cd build
        ./proj2
    - name: valgrind
      run: |
        apt install valgrind
        valgrind ./proj2
